### ISSUE TITLE
a mistake

### ISSUE THREAD

**Issue by telppa** [jNizM/AutoHotkey_MSDN_Types#2]
i checked the BaseTsd.h

`DATA_TYPES["UINT64"] := ["UINT64","Int64","",8,8,"typedef usigned __int 64 UINT64"]`

should be

`DATA_TYPES["UINT64"] := ["UINT64","Int64","",8,8,"typedef unsigned __int64 UINT64"]`

**Comment by jNizM** [comment]
Thank you for reporting.
Looks like the MSDN-Page has still the misstype (https://docs.microsoft.com/en-us/windows/win32/winprog/windows-data-types)

Feel free to report this too (https://github.com/MicrosoftDocs/win32/blob/docs/desktop-src/WinProg/windows-data-types.md)
